export const products = [
  {
    id: 1,
    image: "moisturizing-mousse",
    skinType: "для нормальной кожи",
    title: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    composition: [
      "активные натуральные комплексы",
      "витамины C, A, PP, B и E",
      "солнцезащитные компоненты",
    ],
    price: 2750,
  },
  {
    id: 2,
    image: "moisturizing-mask",
    skinType: "для нормальной кожи",
    title: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    composition: [
      "воски",
      "минералы",
      "масла",
    ],
    price: 3500,
  },
  {
    id: 3,
    image: "cleansing-gel",
    skinType: "для нормальной кожи",
    title: "Гель для умывания",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    composition: [
      "минералы",
      "витамины С, А, РР, В И Е", 
      "солнцезащитные компоненты",
    ],
    price: 1650,
  },
  {
    id: 4,
    image: "gift-set-one",
    skinType: "для нормальной кожи",
    title: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    composition: [
      "воски",
      "минералы", 
      "масла",
    ],
    price: 4750,
  },
  {
    id: 5,
    image: "gift-set-five",
    skinType: "для нормальной кожи",
    title: "Подарочный набор №5",
    description: "Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    composition: [
      "воски",
      "минералы",
      "масла",
    ],
    price: 7520,
  },      
];